// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektManager.DataBaseAPI;

#nullable disable

namespace ProjektManager.Migrations
{
    [DbContext(typeof(ProjektDBContext))]
    [Migration("20240213113928_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbteilungDTOProjektDTO", b =>
                {
                    b.Property<string>("AbteilungenAbBezeichung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjekteProjektNr")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AbteilungenAbBezeichung", "ProjekteProjektNr");

                    b.HasIndex("ProjekteProjektNr");

                    b.ToTable("AbteilungDTOProjektDTO");
                });

            modelBuilder.Entity("ProjektManager.DTOs.AbteilungDTO", b =>
                {
                    b.Property<string>("AbBezeichung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AbLeiter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AbBezeichung");

                    b.ToTable("Abteilungen");
                });

            modelBuilder.Entity("ProjektManager.DTOs.MitarbeiterDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AbteilungDTOAbBezeichung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungDTOAbBezeichung");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProblemDTO", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AbteilungAbBezeichung")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("AuftrittsDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bewertung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bezug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Initiator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KW")
                        .HasColumnType("int");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Maßnahme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjektDTOProjektNr")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProjektNr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProzessStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReTermin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Termin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Thema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungAbBezeichung");

                    b.HasIndex("ProjektDTOProjektNr");

                    b.ToTable("Probleme");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProjektDTO", b =>
                {
                    b.Property<string>("ProjektNr")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Auftraggeber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfTheEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjektLeiter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Stand")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Startpunkt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjektNr");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("AbteilungDTOProjektDTO", b =>
                {
                    b.HasOne("ProjektManager.DTOs.AbteilungDTO", null)
                        .WithMany()
                        .HasForeignKey("AbteilungenAbBezeichung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektManager.DTOs.ProjektDTO", null)
                        .WithMany()
                        .HasForeignKey("ProjekteProjektNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjektManager.DTOs.MitarbeiterDTO", b =>
                {
                    b.HasOne("ProjektManager.DTOs.AbteilungDTO", null)
                        .WithMany("Mitarbeiter")
                        .HasForeignKey("AbteilungDTOAbBezeichung");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProblemDTO", b =>
                {
                    b.HasOne("ProjektManager.DTOs.AbteilungDTO", "Abteilung")
                        .WithMany("Probleme")
                        .HasForeignKey("AbteilungAbBezeichung");

                    b.HasOne("ProjektManager.DTOs.ProjektDTO", null)
                        .WithMany("Probleme")
                        .HasForeignKey("ProjektDTOProjektNr");

                    b.Navigation("Abteilung");
                });

            modelBuilder.Entity("ProjektManager.DTOs.AbteilungDTO", b =>
                {
                    b.Navigation("Mitarbeiter");

                    b.Navigation("Probleme");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProjektDTO", b =>
                {
                    b.Navigation("Probleme");
                });
#pragma warning restore 612, 618
        }
    }
}
