// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektManager.DataBaseAPI;

#nullable disable

namespace ProjektManager.Migrations
{
    [DbContext(typeof(ProjektDBContext))]
    [Migration("20240305100127_NewInti")]
    partial class NewInti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjektManager.DTOs.MitarbeiterDTO", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProblemDTO", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abteilung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AuftrittsDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bewertung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bezug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("InitiatorId")
                        .HasColumnType("int");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Maßnahme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjektDTOProjektNr")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProzessStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReTermin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Termin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Thema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VerantwortlicherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ProjektDTOProjektNr");

                    b.HasIndex("VerantwortlicherId");

                    b.ToTable("Probleme");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProjektDTO", b =>
                {
                    b.Property<string>("ProjektNr")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Auftraggeber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfTheEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjektLeiter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Stand")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Startpunkt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjektNr");

                    b.ToTable("Projekte");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProblemDTO", b =>
                {
                    b.HasOne("ProjektManager.DTOs.MitarbeiterDTO", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId");

                    b.HasOne("ProjektManager.DTOs.ProjektDTO", null)
                        .WithMany("Probleme")
                        .HasForeignKey("ProjektDTOProjektNr");

                    b.HasOne("ProjektManager.DTOs.MitarbeiterDTO", "Verantwortlicher")
                        .WithMany()
                        .HasForeignKey("VerantwortlicherId");

                    b.Navigation("Initiator");

                    b.Navigation("Verantwortlicher");
                });

            modelBuilder.Entity("ProjektManager.DTOs.ProjektDTO", b =>
                {
                    b.Navigation("Probleme");
                });
#pragma warning restore 612, 618
        }
    }
}
